logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: ch15-ex4-rs
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8082

server:
  port: 8081