logging:
  level:
    org.springframework.security: trace

server:
  port: 9090

spring:
  application:
    name: ch13-ex2
  security:
    user:
      name: john
      password: 12345
    oauth2:
      authorizationserver:
        client:
          test-client:
            registration:
              client-id: "test-client"
              client-secret: "{noop}test-secret"
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              scopes:
                - read
              redirect-uris:
                - http://localhost:8080/oauth2/after-authorize
              post-logout-redirect-uris:
                - http://localhost:8080/logout
            require-authorization-consent: true
#        issuer: http://auth-server.com:9000